
---
- name: install default apache web server
  hosts: all
  become: yes


  tasks:
  - name: install apache web server
    apt: name=apache2 state=latest


  - name: start apache and enable it on every boot
    service: name=apache2 state=started enabled=yes
