
---

- name: errorhandling
  hosts: all
  any_errors_fatal: true
  become: yes

  tasks:
  - name: task 1
    apt: name=treeeeeee state=latest
    ignore_errors: yes

  - name: task 2
#    shell: ls -la /etc/
#    shell: hello world !!!!
    shell: cat /home/vova/myfile.txt
    register: results
#    failed_when: results.rc == 0
#    failed_when: "'world' in results.stdout"

  - debug:
      var: results

  - name: task 3
    shell: echo shalom olam!

