
---
- name: import/include modules playbook
  hosts: all
  become: yes

  vars:
   mytext: "hi from vova"

  tasks:
  - name: ping test
    ping:
  
#  - name: create folders
  - include: create_folders.yml
   
#  - name: create files
  - include: create_files.yml mytext="hello from tlv" 
