
---
- name: install apache and ipload my web page
  hosts: all
  become: yes

  vars:
    source_file: ./mywebsite/index.html
    dest_file: /var/www/html

  tasks:
  - name: install apache web server
    apt: name=apache2 state=latest

  - name: copy myhomepage to servers
    copy: src={{ source_file }} dest={{ dest_file }} mode=0555
    notify: restart apache
 
  - name: start webserver and make it enable on boot
    service: name=apache2 state=started enabled=yes

  handlers:
  - name : restart apache
    service: name=apache2 state=restarted
